name: EAS Build Client
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo and EAS
        working-directory: ./client
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Build on EAS
        working-directory: ./client
        run: eas build --platform android --non-interactive